{{- if .Values.ingress.enabled -}}
{{- $fullName := include "my-bloody-jenkins.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "my-bloody-jenkins.name" . }}
    chart: {{ template "my-bloody-jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if or .Values.ingress.tls (and .Values.ingress.tls.certificate .Values.ingress.tls.privateKey) }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
{{- if .Values.ingress.tls }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- else }}
      secretName: {{ template "my-bloody-jenkins.tlsSecretName" . }}
{{- end }}
{{- end }}
  rules:
  - host: {{ required ".Values.ingress.hostname is required!" .Values.ingress.hostname }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
{{- if .Values.ingress.additionalRules }}
{{ toYaml .Values.ingress.additionalRules | indent 2 }}
{{- end }}
{{- end }}
