{{- if .Values.rbac.create }}
{{- $fullName := include "my-bloody-jenkins.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
{{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

---
kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ $fullName }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRoleBinding"{{ else }}"RoleBinding"{{ end }}
metadata:
  name: {{ $fullName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
  name: {{ $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}
  namespace: "{{ .Release.Namespace }}"
{{- end }}
